version: '3.8'

services:
  mojo:
    container_name: mojo
    build:
      context: .
      dockerfile: Dockerfile.mojosdk
      args:
        - AUTH_KEY=1Auth_token
      no_cache : true
    ports:
      - 8080:8080
    volumes:
      - ./..:/mojo
    working_dir: /mojo 
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]